### ISSUE TITLE
Segfaults if started from command line without content 

### ISSUE THREAD

**Issue by orbea** [libretro/flycast#7]
## Description

reicast will segfault if started from the command line while failing to specify any content.

This may be related to this RetroArch issue which should now be fixed (As seen with other cores) except reicast is still broken.
https://github.com/libretro/RetroArch/issues/4493

### Expected behavior

reicast should not segfault and should fail safely.

### Actual behavior

```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007fffe9689cd6 in dc_term () at core/nullDC.cpp:241
#2  0x00007fffeab94fb1 in retro_deinit () at core/libretro/libretro.cpp:214
#3  0x00000000004127fb in core_unload () at core_impl.c:397
#4  0x0000000000419b2c in command_event_deinit_core (reinit=true)
    at command.c:1202
#5  0x000000000041ba2d in command_event (cmd=CMD_EVENT_CORE_DEINIT, data=0x0)
    at command.c:2260
#6  0x0000000000414b75 in retroarch_main_init (argc=3, argv=0x7fffffffe1b8)
    at retroarch.c:1114
#7  0x0000000000428a33 in content_load (info=0x7fffffffe080)
    at tasks/task_content.c:278
#8  0x0000000000429be4 in task_load_content (content_info=0x7fffffffe080, 
    content_ctx=0x7fffffffdff0, launched_from_menu=false, mode=
    CONTENT_MODE_LOAD_FROM_CLI, error_string=0x7fffffffdfe8)
    at tasks/task_content.c:832
#9  0x000000000042a431 in task_push_content_load_default (core_path=0x0, 
    fullpath=0x0, content_info=0x7fffffffe080, type=CORE_TYPE_PLAIN, mode=
    CONTENT_MODE_LOAD_FROM_CLI, cb=0x0, user_data=0x0)
    at tasks/task_content.c:1253
#10 0x00000000004113af in rarch_main (argc=3, argv=0x7fffffffe1b8, data=0x0)
    at frontend/frontend.c:113
#11 0x0000000000411440 in main (argc=3, argv=0x7fffffffe1b8)
    at frontend/frontend.c:148
```
Full GDB log - http://pastebin.com/PVYX3LVZ

### Steps to reproduce the bug

1. `retroarch -L reicast_libretro.so`
2. Segfault...

### Version/Commit

`RetroArch-2017.01.25_31fab1979_master-x86_64-1_git`
`libretro-reicast-2017.01.24_4cf27c43_master-x86_64-1_git`

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-5.4.0`

**Comment by orbea** [comment]
This was a RetroArch issue and has been fixed.
