### ISSUE TITLE
[chd] Music CDs

### ISSUE THREAD

**Issue by telanus** [libretro/flycast#895]
when one load a Music CD that's in the chd Flycast causes RA to crash.

##Case 1 
When you run flycast via the gui it'll load the up as normal, but won't recognize the cd, and crash when exiting as described here: https://github.com/libretro/RetroArch/issues/10651

##Case 2
When loading it via gdb, it'll never get to the boot screen but crash with the following error:

`Thread 10 "retroarch" received signal SIGSEGV, Segmentation fault.
`

And bt gives the following:

```
bt
#0  0x00007fffcdbc6952 in  () at ~/gamez/retroarch/cores/flycast_libretro.so
#1  0x00007fffcdbc6997 in  () at ~/gamez/retroarch/cores/flycast_libretro.so
#2  0x00007fffcca8f467 in  () at ~/gamez/retroarch/cores/flycast_libretro.so
#3  0x00007fffcff44020 in  () at ~/gamez/retroarch/cores/flycast_libretro.so
#4  0x00007fffffffdb90 in  ()
#5  0x0000555556b19650 in  ()
#6  0x0000000000000000 in  ()
```

The following also get printed while RA starts:

`[libretro WARN] 00:01:021 imgread/chd.cpp:173 W[GDROM]: WARNING: chd: Total frames is wrong: 246690 frames in 15 tracks`

So it sees the 15 tracks in the music cd but can't differentiate between a dreamcast disc and a music cd

**Comment by flyinghead** [comment]
Right now flycast only supports CHDs for GD-Roms, not Audio CDs or MIL-CDs
